### ISSUE TITLE
No build for 1.7.9

### ISSUE THREAD

**Issue by gitgizmo7** [Augmentedjs/balena-io-etcher-builds#2]

**Comment by thedocbwarren** [comment]
Correct, there were no changes for 1.7.9 as it was a change for Ubuntu.  I had tried to build anyway to version bump without success.  Given there isn't a single change in the macOS codebase I didn't feel it was worth a lot of trouble.  I did attempt to diagnose the build issue without success.

**Comment by thedocbwarren** [comment]
Will make a build when the next version is available with changes in macOS.
