### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by ryanfortner** [Augmentedjs/balena-io-etcher-builds#3]
Hi there,

Thanks for starting this repository! It's really helpful to have native builds :). Do you mind sharing your steps for building the software? Are there any additional steps, patches, or workarounds required?

**Comment by thedocbwarren** [comment]
It's mostly simple:

- npm install
- Check if all native modules “node-gyp”-ed correctly
- If not go to the folder of the module (inside node_modules) and run electron-rebuild
- npm run webpack

* Builds will only be signed if using an Apple Developer account.

Output .dmg file will be located in the dist folder if all went well.  

The 1.7.9 build does not seem to build a dmg though.  I have not been able to diagnose the issue.

**Comment by ryanfortner** [comment]
Thanks for your response. I recently purchased an Apple silicon laptop and I may be able to do some troubleshooting at some point.

**Comment by thedocbwarren** [comment]
> Thanks for your response. I recently purchased an Apple silicon laptop and I may be able to do some troubleshooting at some point.

Definitely welcome the collaboration.  I'm not officially part of the team but enjoy helping in the AS community.
